(() => {
  "use strict";
  const echoCatalog = [
    {"key":"BellBorneGeochelone","name":"Bell-Borne Geochelone","cost":4,"sets":["rejuvenating-glow","moonlit-clouds"],"id":"bell-borne-geochelone"},
    {"key":"Crownless","name":"Crownless","cost":4,"sets":["havoc-eclipse"],"id":"crownless"},
    {"key":"DragonofDirge","name":"Dragon of Dirge","cost":4,"sets":["tidebreaking-courage"],"id":"dragon-of-dirge"},
    {"key":"Dreamless","name":"Dreamless","cost":4,"sets":["havoc-eclipse"],"id":"dreamless"},
    {"key":"FallacyOfNoReturn","name":"Fallacy of No Return","cost":4,"sets":["rejuvenating-glow"],"id":"fallacy-of-no-return"},
    {"key":"FeilianBeringal","name":"Feilian Beringal","cost":4,"sets":["sierra-gale"],"id":"feilian-beringal"},
    {"key":"Hecate","name":"Hecate","cost":4,"sets":["empyrean-anthem"],"id":"hecate"},
    {"key":"Hyvatia","name":"Hyvatia","cost":4,"sets":["pact-of-neonlight-leap","rite-of-gilded-revelation"],"id":"hyvatia"},
    {"key":"ImpermanenceHeron","name":"Impermanence Heron","cost":4,"sets":["moonlit-clouds"],"id":"impermanence-heron"},
    {"key":"InfernoRider","name":"Inferno Rider","cost":4,"sets":["molten-rift"],"id":"inferno-rider"},
    {"key":"Jue","name":"Jué","cost":4,"sets":["celestial-light"],"id":"jue","asset":"Jue"},
    {"key":"LadyoftheSea","name":"Lady of the Sea","cost":4,"sets":["crown-of-valor"],"id":"lady-of-the-sea"},
    {"key":"LampylumenMyriad","name":"Lampylumen Myriad","cost":4,"sets":["freezing-frost"],"id":"lampylumen-myriad"},
    {"key":"LionessofGlory","name":"Lioness of Glory","cost":4,"sets":["flaming-clawprint"],"id":"lioness-of-glory"},
    {"key":"Lorelei","name":"Lorelei","cost":4,"sets":["midnight-veil"],"id":"lorelei"},
    {"key":"MechAbomination","name":"Mech Abomination","cost":4,"sets":["lingering-tunes"],"id":"mech-abomination"},
    {"key":"MourningAix","name":"Mourning Aix","cost":4,"sets":["celestial-light"],"id":"mourning-aix"},
    {"key":"MyriadSnareRustfireChassis","name":"Myriad Snare: Rustfire Chassis","cost":4,"sets":["heart-of-evils-purge","lamp-of-nether-road"],"id":"myriad-snare-rustfire-chassis"},
    {"key":"NamelessExplorer","name":"Nameless Explorer","cost":4,"sets":["sound-of-true-name","reel-of-spliced-memories"],"id":"nameless-explorer"},
    {"key":"NightmareCrownless","name":"Nightmare: Crownless","cost":4,"sets":["havoc-eclipse"],"id":"nightmare-crownless"},
    {"key":"NightmareFeilianBeringal","name":"Nightmare: Feilian Beringal","cost":4,"sets":["sierra-gale"],"id":"nightmare-feilian-beringal"},
    {"key":"NightmareHecate","name":"Nightmare: Hecate","cost":4,"sets":["dream-of-the-lost"],"id":"nightmare-hecate"},
    {"key":"NightmareImpermanenceHeron","name":"Nightmare: Impermanence Heron","cost":4,"sets":["midnight-veil"],"id":"nightmare-impermanence-heron"},
    {"key":"NightmareInfernoRider","name":"Nightmare: Inferno Rider","cost":4,"sets":["molten-rift"],"id":"nightmare-inferno-rider"},
    {"key":"NightmareKelpie","name":"Nightmare: Kelpie","cost":4,"sets":["gusts-of-welkin","windward-pilgrimage"],"id":"nightmare-kelpie"},
    {"key":"NightmareLampylumenMyriad","name":"Nightmare: Lampylumen Myriad","cost":4,"sets":["frosty-resolve","empyrean-anthem"],"id":"nightmare-lampylumen-myriad"},
    {"key":"NightmareMourningAix","name":"Nightmare: Mourning Aix","cost":4,"sets":["eternal-radiance"],"id":"nightmare-mourning-aix"},
    {"key":"NightmareTempestMephis","name":"Nightmare: Tempest Mephis","cost":4,"sets":["empyrean-anthem","void-thunder"],"id":"nightmare-tempest-mephis"},
    {"key":"NightmareThunderingMephis","name":"Nightmare: Thundering Mephis","cost":4,"sets":["void-thunder"],"id":"nightmare-thundering-mephis"},
    {"key":"ReactorHusk","name":"Reactor Husk","cost":4,"sets":["halo-of-starry-radiance","chromatic-foam"],"id":"reactor-husk"},
    {"key":"ReminiscenceNightmareAdamSmasher","name":"Reminiscence - Nightmare: Adam Smasher","cost":4,"sets":["shadow-of-shattered-dreams"],"id":"nightmare-adam-smasher"},
    {"key":"ReminiscenceDenia","name":"Reminiscence: Denia","cost":4,"sets":["chromatic-foam"],"id":"reminiscence-denia"},
    {"key":"ReminiscenceFenrico","name":"Reminiscence: Fenrico","cost":4,"sets":["dream-of-the-lost","law-of-harmony"],"id":"reminiscence-fenrico"},
    {"key":"ReminiscenceFleurdelys","name":"Reminiscence: Fleurdelys","cost":4,"sets":["windward-pilgrimage","gusts-of-welkin"],"id":"reminiscence-fleurdelys"},
    {"key":"ReminiscenceThrenodianLeviathan","name":"Reminiscence: Threnodian - Leviathan","cost":4,"sets":["thread-of-severed-fate","flamewings-shadow"],"id":"threnodian-leviathan"},
    {"key":"ReminiscenceThrenodianVoidborneConstruct","name":"Reminiscence: Threnodian - Voidborne Construct","cost":4,"sets":["wishes-of-quiet-snowfall"],"id":"threnodian-voidborne-construct"},
    {"key":"SentryConstruct","name":"Sentry Construct","cost":4,"sets":["frosty-resolve"],"id":"sentry-construct"},
    {"key":"Sigillum","name":"Sigillum","cost":4,"sets":["trailblazing-star"],"id":"sigillum"},
    {"key":"TempestMephis","name":"Tempest Mephis","cost":4,"sets":["void-thunder"],"id":"tempest-mephis"},
    {"key":"TheFalseSovereign","name":"The False Sovereign","cost":4,"sets":["crown-of-valor"],"id":"the-false-sovereign"},
    {"key":"ThousandPuppetPavilion","name":"Thousand-Puppet Pavilion","cost":4,"sets":["song-of-feathered-trace"],"id":"thousand-puppet-pavilion"},
    {"key":"ThunderingMephis","name":"Thundering Mephis","cost":4,"sets":["void-thunder"],"id":"thundering-mephis"},
    {"key":"AbyssalGladius","name":"Abyssal Gladius","cost":3,"sets":["tidebreaking-courage","midnight-veil","thread-of-severed-fate"]},
    {"key":"AbyssalMercator","name":"Abyssal Mercator","cost":3,"sets":["frosty-resolve","eternal-radiance"]},
    {"key":"AbyssalPatricius","name":"Abyssal Patricius","cost":3,"sets":["empyrean-anthem","frosty-resolve"]},
    {"key":"AutopuppetScout","name":"Autopuppet Scout","cost":3,"sets":["celestial-light","freezing-frost"]},
    {"key":"Capitaneus","name":"Capitaneus","cost":3,"sets":["gusts-of-welkin","eternal-radiance","windward-pilgrimage"],"id":"capitaneus"},
    {"key":"Carapace","name":"Carapace","cost":3,"sets":["moonlit-clouds","sierra-gale"]},
    {"key":"ChasmGuardian","name":"Chasm Guardian","cost":3,"sets":["lingering-tunes","rejuvenating-glow"]},
    {"key":"ChopChop","name":"Chop Chop","cost":3,"sets":["tidebreaking-courage","empyrean-anthem","dream-of-the-lost"]},
    {"key":"Corrosaurus","name":"Corrosaurus","cost":3,"sets":["flaming-clawprint","flamewings-shadow"],"id":"corrosaurus"},
    {"key":"CuddleWuddle","name":"Cuddle Wuddle","cost":3,"sets":["frosty-resolve","midnight-veil"]},
    {"key":"CyanFeatheredHeron","name":"Cyan-Feathered Heron","cost":3,"sets":["sierra-gale","celestial-light"]},
    {"key":"DiurnusKnight","name":"Diurnus Knight","cost":3,"sets":["eternal-radiance","tidebreaking-courage"],"id":"diurnus-knight"},
    {"key":"Flautist","name":"Flautist","cost":3,"sets":["void-thunder","lingering-tunes"]},
    {"key":"FloraReindeer","name":"Flora Reindeer","cost":3,"sets":["rite-of-gilded-revelation","reel-of-spliced-memories"]},
    {"key":"FogLionarch","name":"Fog Lionarch","cost":3,"sets":["song-of-feathered-trace","heart-of-evils-purge","lamp-of-nether-road"]},
    {"key":"ForbiddenBastion","name":"Forbidden Bastion","cost":3,"sets":["song-of-feathered-trace","heart-of-evils-purge","lamp-of-nether-road"],"id":"forbidden-bastion"},
    {"key":"FrostbiteColeoid","name":"Frostbite Coleoid","cost":3,"sets":["halo-of-starry-radiance","wishes-of-quiet-snowfall"]},
    {"key":"GlacioDreadmane","name":"Glacio Dreadmane","cost":3,"sets":["moonlit-clouds","freezing-frost"],"id":"glacio-dreadmane"},
    {"key":"Glommoth","name":"Glommoth","cost":3,"sets":["trailblazing-star","wishes-of-quiet-snowfall"],"id":"glommoth"},
    {"key":"HavocDreadmane","name":"Havoc Dreadmane","cost":3,"sets":["molten-rift","havoc-eclipse"],"id":"havoc-dreadmane"},
    {"key":"Hoochief","name":"Hoochief","cost":3,"sets":["rejuvenating-glow","sierra-gale"],"id":"hoochief"},
    {"key":"Hurriclaw","name":"Hurriclaw","cost":3,"sets":["tidebreaking-courage","gusts-of-welkin","crown-of-valor"]},
    {"key":"Ironhoof","name":"Ironhoof","cost":3,"sets":["pact-of-neonlight-leap","wishes-of-quiet-snowfall","reel-of-spliced-memories"],"id":"ironhoof"},
    {"key":"Kerasaur","name":"Kerasaur","cost":3,"sets":["windward-pilgrimage","flaming-clawprint","flamewings-shadow"]},
    {"key":"Kronablight","name":"Kronablight","cost":3,"sets":["trailblazing-star","chromatic-foam"]},
    {"key":"Lightcrusher","name":"Lightcrusher","cost":3,"sets":["celestial-light"],"id":"lightcrusher"},
    {"key":"LumiscaleConstruct","name":"Lumiscale Construct","cost":3,"sets":["void-thunder","freezing-frost"],"id":"lumiscale-construct"},
    {"key":"MiningReindeer","name":"Mining Reindeer","cost":3,"sets":["pact-of-neonlight-leap","reel-of-spliced-memories"],"id":"mining-reindeer"},
    {"key":"NightmareCyanFeatheredHeron","name":"Nightmare: Cyan-Feathered Heron","cost":3,"sets":["law-of-harmony"]},
    {"key":"NightmareRoseshroom","name":"Nightmare: Roseshroom","cost":3,"sets":["thread-of-severed-fate"]},
    {"key":"NightmareTambourinist","name":"Nightmare: Tambourinist","cost":3,"sets":["dream-of-the-lost"]},
    {"key":"NightmareVioletFeatheredHeron","name":"Nightmare: Violet-Feathered Heron","cost":3,"sets":["crown-of-valor"],"id":"nightmare-violet-feathered-heron"},
    {"key":"NightmareViridblazeSaurian","name":"Nightmare: Viridblaze Saurian","cost":3,"sets":["flamewings-shadow"]},
    {"key":"NocturnusKnight","name":"Nocturnus Knight","cost":3,"sets":["midnight-veil","empyrean-anthem"]},
    {"key":"PilgrimsShell","name":"Pilgrim's Shell","cost":3,"sets":["windward-pilgrimage","flaming-clawprint"]},
    {"key":"QuestlessKnight","name":"Questless Knight","cost":3,"sets":["frosty-resolve","midnight-veil"]},
    {"key":"RageAgainstTheStatue","name":"Rage Against the Statue","cost":3,"sets":["eternal-radiance","gusts-of-welkin","law-of-harmony"],"id":"rage-against-the-statue"},
    {"key":"ReminiscenceKronaclaw","name":"Reminiscence: Kronaclaw","cost":3,"sets":["trailblazing-star","chromatic-foam"]},
    {"key":"RocksteadyGuardian","name":"Rocksteady Guardian","cost":3,"sets":["rejuvenating-glow","celestial-light"]},
    {"key":"Roseshroom","name":"Roseshroom","cost":3,"sets":["freezing-frost","havoc-eclipse"],"id":"roseshroom"},
    {"key":"SabercatProwler","name":"Sabercat Prowler","cost":3,"sets":["pact-of-neonlight-leap","halo-of-starry-radiance","sound-of-true-name"]},
    {"key":"SabercatReaver","name":"Sabercat Reaver","cost":3,"sets":["pact-of-neonlight-leap","halo-of-starry-radiance","sound-of-true-name"]},
    {"key":"SpacetrekExplorer","name":"Spacetrek Explorer","cost":3,"sets":["halo-of-starry-radiance","chromatic-foam","sound-of-true-name"]},
    {"key":"Spearback","name":"Spearback","cost":3,"sets":["lingering-tunes","moonlit-clouds"]},
    {"key":"StonewallBracer","name":"Stonewall Bracer","cost":3,"sets":["rejuvenating-glow","moonlit-clouds"]},
    {"key":"Tambourinist","name":"Tambourinist","cost":3,"sets":["freezing-frost","havoc-eclipse"],"id":"tambourinist"},
    {"key":"TwinNovaCollapsarBlade","name":"Twin Nova: Collapsar Blade","cost":3,"sets":["rite-of-gilded-revelation","trailblazing-star","sound-of-true-name"]},
    {"key":"TwinNovaNebulousCannon","name":"Twin Nova: Nebulous Cannon","cost":3,"sets":["rite-of-gilded-revelation","chromatic-foam"],"id":"twin-nova-nebulous-cannon"},
    {"key":"VioletFeatheredHeron","name":"Violet-Feathered Heron","cost":3,"sets":["molten-rift","void-thunder"]},
    {"key":"ViridblazeSaurian","name":"Viridblaze Saurian","cost":3,"sets":["moonlit-clouds","molten-rift"]},
    {"key":"VitreumDancer","name":"Vitreum Dancer","cost":3,"sets":["empyrean-anthem","eternal-radiance"],"id":"vitreum-dancer"},
    {"key":"VoidwingMoth","name":"Voidwing Moth","cost":3,"sets":["reel-of-spliced-memories"],"id":"voidwing-moth"},
    {"key":"WindlashColeoid","name":"Windlash Coleoid","cost":3,"sets":["rite-of-gilded-revelation","wishes-of-quiet-snowfall"],"id":"windlash-coleoid"},
    {"key":"AeroDrake","name":"Aero Drake","cost":1,"sets":["gusts-of-welkin","tidebreaking-courage","flaming-clawprint"]},
    {"key":"AeroPredator","name":"Aero Predator","cost":1,"sets":["void-thunder","sierra-gale"]},
    {"key":"AeroPrism","name":"Aero Prism","cost":1,"sets":["eternal-radiance","tidebreaking-courage"]},
    {"key":"AureatePicket","name":"Aureate Picket","cost":1,"sets":["heart-of-evils-purge"],"id":"aureate-picket"},
    {"key":"BabyRoseshroom","name":"Baby Roseshroom","cost":1,"sets":["sierra-gale","havoc-eclipse"],"id":"baby-roseshroom"},
    {"key":"BabyViridblazeSaurian","name":"Baby Viridblaze Saurian","cost":1,"sets":["lingering-tunes","void-thunder","molten-rift"]},
    {"key":"CalcifiedJunrock","name":"Calcified Junrock","cost":1,"sets":["tidebreaking-courage","empyrean-anthem","crown-of-valor"]},
    {"key":"ChestMimic","name":"Chest Mimic","cost":1,"sets":["midnight-veil","empyrean-anthem","frosty-resolve"]},
    {"key":"Chirpuff","name":"Chirpuff","cost":1,"sets":["havoc-eclipse","sierra-gale"]},
    {"key":"ChopChopHeadless","name":"Chop Chop: Headless","cost":1,"sets":["eternal-radiance","tidebreaking-courage"]},
    {"key":"ChopChopLeftless","name":"Chop Chop: Leftless","cost":1,"sets":["frosty-resolve","tidebreaking-courage"]},
    {"key":"ChopChopRightless","name":"Chop Chop: Rightless","cost":1,"sets":["tidebreaking-courage","frosty-resolve"]},
    {"key":"ClangBang","name":"Clang Bang","cost":1,"sets":["celestial-light","freezing-frost"]},
    {"key":"Cruisewing","name":"Cruisewing","cost":1,"sets":["rejuvenating-glow","moonlit-clouds","celestial-light"]},
    {"key":"DevoteesFlesh","name":"Devotee's Flesh","cost":1,"sets":["gusts-of-welkin","windward-pilgrimage","flaming-clawprint"],"id":"devotees-flesh"},
    {"key":"Diamondclaw","name":"Diamondclaw","cost":1,"sets":["moonlit-clouds","lingering-tunes"],"id":"diamondclaw"},
    {"key":"DiggyDuggy","name":"Diggy Duggy","cost":1,"sets":["eternal-radiance","tidebreaking-courage"],"id":"diggy-duggy"},
    {"key":"DwarfCassowary","name":"Dwarf Cassowary","cost":1,"sets":["sierra-gale","rejuvenating-glow"]},
    {"key":"ElectroDrake","name":"Electro Drake","cost":1,"sets":["gusts-of-welkin","midnight-veil","flaming-clawprint"]},
    {"key":"ElectroPredator","name":"Electro Predator","cost":1,"sets":["molten-rift","void-thunder"]},
    {"key":"Excarat","name":"Excarat","cost":1,"sets":["freezing-frost","havoc-eclipse"]},
    {"key":"FaeIgnis","name":"Fae Ignis","cost":1,"sets":["midnight-veil","eternal-radiance","dream-of-the-lost"]},
    {"key":"FissionJunrock","name":"Fission Junrock","cost":1,"sets":["moonlit-clouds","void-thunder","rejuvenating-glow"]},
    {"key":"FloraDrone","name":"Flora Drone","cost":1,"sets":["pact-of-neonlight-leap","rite-of-gilded-revelation","sound-of-true-name","reel-of-spliced-memories"]},
    {"key":"FogLionarchBody","name":"Fog Lionarch: Body","cost":1,"sets":["song-of-feathered-trace"]},
    {"key":"FogLionarchHead","name":"Fog Lionarch: Head","cost":1,"sets":["song-of-feathered-trace"]},
    {"key":"FrostscourgeStalker","name":"Frostscourge Stalker","cost":1,"sets":["midnight-veil","eternal-radiance"]},
    {"key":"FusionDrake","name":"Fusion Drake","cost":1,"sets":["flaming-clawprint","windward-pilgrimage"],"id":"fusion-drake"},
    {"key":"FusionDreadmane","name":"Fusion Dreadmane","cost":1,"sets":["rejuvenating-glow","molten-rift"],"id":"fusion-dreadmane"},
    {"key":"FusionPrism","name":"Fusion Prism","cost":1,"sets":["freezing-frost","lingering-tunes","molten-rift"]},
    {"key":"FusionWarrior","name":"Fusion Warrior","cost":1,"sets":["sierra-gale","void-thunder","molten-rift"]},
    {"key":"GalescourgeStalker","name":"Galescourge Stalker","cost":1,"sets":["frosty-resolve","empyrean-anthem"]},
    {"key":"GeospiderS4","name":"Geospider S4","cost":1,"sets":["pact-of-neonlight-leap","halo-of-starry-radiance","trailblazing-star"]},
    {"key":"GlacioDrake","name":"Glacio Drake","cost":1,"sets":["gusts-of-welkin","windward-pilgrimage"]},
    {"key":"GlacioPredator","name":"Glacio Predator","cost":1,"sets":["celestial-light","freezing-frost"]},
    {"key":"GlacioPrism","name":"Glacio Prism","cost":1,"sets":["havoc-eclipse","moonlit-clouds","freezing-frost"]},
    {"key":"GoldenJunrock","name":"Golden Junrock","cost":1,"sets":["eternal-radiance","frosty-resolve","law-of-harmony"],"id":"golden-junrock"},
    {"key":"Gulpuff","name":"Gulpuff","cost":1,"sets":["celestial-light","freezing-frost"],"id":"gulpuff"},
    {"key":"HavocDrake","name":"Havoc Drake","cost":1,"sets":["flaming-clawprint","windward-pilgrimage","thread-of-severed-fate"]},
    {"key":"HavocPrism","name":"Havoc Prism","cost":1,"sets":["void-thunder","celestial-light","havoc-eclipse"]},
    {"key":"HavocWarrior","name":"Havoc Warrior","cost":1,"sets":["celestial-light","havoc-eclipse"]},
    {"key":"Hoartoise","name":"Hoartoise","cost":1,"sets":["celestial-light","freezing-frost"]},
    {"key":"HocusPocus","name":"Hocus Pocus","cost":1,"sets":["frosty-resolve","empyrean-anthem"]},
    {"key":"Hooscamp","name":"Hooscamp","cost":1,"sets":["lingering-tunes","sierra-gale"]},
    {"key":"IceglintDancer","name":"Iceglint Dancer","cost":1,"sets":["trailblazing-star","wishes-of-quiet-snowfall","reel-of-spliced-memories"]},
    {"key":"KernelPuppetAnger","name":"Kernel Puppet: Anger","cost":1,"sets":["heart-of-evils-purge"],"id":"kernel-puppet-anger"},
    {"key":"KernelPuppetFright","name":"Kernel Puppet: Fright","cost":1,"sets":["lamp-of-nether-road"],"id":"kernel-puppet-fright"},
    {"key":"KernelPuppetGrief","name":"Kernel Puppet: Grief","cost":1,"sets":["lamp-of-nether-road"],"id":"kernel-puppet-grief"},
    {"key":"KernelPuppetJoy","name":"Kernel Puppet: Joy","cost":1,"sets":["song-of-feathered-trace"],"id":"kernel-puppet-joy"},
    {"key":"KernelPuppetReflection","name":"Kernel Puppet: Reflection","cost":1,"sets":["heart-of-evils-purge"],"id":"kernel-puppet-reflection"},
    {"key":"KernelPuppetWorry","name":"Kernel Puppet: Worry","cost":1,"sets":["heart-of-evils-purge"],"id":"kernel-puppet-worry"},
    {"key":"LaGuardia","name":"La Guardia","cost":1,"sets":["gusts-of-welkin","midnight-veil","flaming-clawprint"]},
    {"key":"LavaLarva","name":"Lava Larva","cost":1,"sets":["lingering-tunes","molten-rift"],"id":"lava-larva"},
    {"key":"LottieLost","name":"Lottie Lost","cost":1,"sets":["tidebreaking-courage","frosty-resolve"]},
    {"key":"MiningDrone","name":"Mining Drone","cost":1,"sets":["halo-of-starry-radiance","rite-of-gilded-revelation","sound-of-true-name","reel-of-spliced-memories"],"id":"mining-drone"},
    {"key":"NightmareAeroPredator","name":"Nightmare: Aero Predator","cost":1,"sets":["crown-of-valor"]},
    {"key":"NightmareBabyRoseshroom","name":"Nightmare: Baby Roseshroom","cost":1,"sets":["flamewings-shadow"]},
    {"key":"NightmareBabyViridblazeSaurian","name":"Nightmare: Baby Viridblaze Saurian","cost":1,"sets":["flamewings-shadow"]},
    {"key":"NightmareChirpuff","name":"Nightmare: Chirpuff","cost":1,"sets":["law-of-harmony"]},
    {"key":"NightmareDwarfCassowary","name":"Nightmare: Dwarf Cassowary","cost":1,"sets":["thread-of-severed-fate"]},
    {"key":"NightmareElectroPredator","name":"Nightmare: Electro Predator","cost":1,"sets":["crown-of-valor"]},
    {"key":"NightmareGlacioPredator","name":"Nightmare: Glacio Predator","cost":1,"sets":["dream-of-the-lost"],"id":"nightmare-glacio-predator"},
    {"key":"NightmareGulpuff","name":"Nightmare: Gulpuff","cost":1,"sets":["law-of-harmony"]},
    {"key":"NightmareHavocWarrior","name":"Nightmare: Havoc Warrior","cost":1,"sets":["dream-of-the-lost"]},
    {"key":"NightmareTickTack","name":"Nightmare: Tick Tack","cost":1,"sets":["thread-of-severed-fate"],"id":"nightmare-tick-tack"},
    {"key":"NimbusWraith","name":"Nimbus Wraith","cost":1,"sets":["empyrean-anthem","midnight-veil","flamewings-shadow"]},
    {"key":"PorcelainPicket","name":"Porcelain Picket","cost":1,"sets":["lamp-of-nether-road"],"id":"porcelain-picket"},
    {"key":"SabyrBoar","name":"Sabyr Boar","cost":1,"sets":["moonlit-clouds","sierra-gale","freezing-frost"],"id":"sabyr-boar"},
    {"key":"Sacerdos","name":"Sacerdos","cost":1,"sets":["gusts-of-welkin","windward-pilgrimage"]},
    {"key":"Sagittario","name":"Sagittario","cost":1,"sets":["gusts-of-welkin","eternal-radiance","flaming-clawprint"]},
    {"key":"ShadowStepper","name":"Shadow Stepper","cost":1,"sets":["trailblazing-star","chromatic-foam","wishes-of-quiet-snowfall"]},
    {"key":"Smiter","name":"Smiter","cost":1,"sets":["song-of-feathered-trace"]},
    {"key":"Smolder","name":"Smolder","cost":1,"sets":["song-of-feathered-trace"]},
    {"key":"SnipSnap","name":"Snip Snap","cost":1,"sets":["lingering-tunes","rejuvenating-glow","molten-rift"]},
    {"key":"SpectroDrake","name":"Spectro Drake","cost":1,"sets":["flaming-clawprint","windward-pilgrimage"]},
    {"key":"SpectroPrism","name":"Spectro Prism","cost":1,"sets":["molten-rift","void-thunder","celestial-light"]},
    {"key":"StonePicket","name":"Stone Picket","cost":1,"sets":["lamp-of-nether-road"],"id":"stone-picket"},
    {"key":"TickTack","name":"Tick Tack","cost":1,"sets":["lingering-tunes","rejuvenating-glow","havoc-eclipse"],"id":"tick-tack"},
    {"key":"TrafficIlluminator","name":"Traffic Illuminator","cost":1,"sets":["void-thunder","sierra-gale","molten-rift"],"id":"traffic-illuminator"},
    {"key":"TremorWarrior","name":"Tremor Warrior","cost":1,"sets":["halo-of-starry-radiance","chromatic-foam","wishes-of-quiet-snowfall"]},
    {"key":"VanguardJunrock","name":"Vanguard Junrock","cost":1,"sets":["rejuvenating-glow","void-thunder","lingering-tunes"]},
    {"key":"VoltscourgeStalker","name":"Voltscourge Stalker","cost":1,"sets":["empyrean-anthem","midnight-veil"],"id":"voltscourge-stalker"},
    {"key":"WhiffWhaff","name":"Whiff Whaff","cost":1,"sets":["rejuvenating-glow","moonlit-clouds","sierra-gale"],"id":"whiff-whaff"},
    {"key":"ZigZag","name":"Zig Zag","cost":1,"sets":["moonlit-clouds","lingering-tunes","celestial-light"],"id":"zig-zag"},
    {"key":"ZipZap","name":"Zip Zap","cost":1,"sets":["pact-of-neonlight-leap","rite-of-gilded-revelation","chromatic-foam","sound-of-true-name"]}
  ];
  window.LOCAL_ECHO_CATALOG = Object.freeze(echoCatalog.map(Object.freeze));
})();
